<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "vt9"
 *
 * Auto generated by Extension Builder 2019-01-09
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'TYPO3 9 Videotraining Sitepackage',
    'description' => '',
    'category' => 'templates',
    'author' => 'Wolfgang Wagner',
    'author_email' => 'videotraining@wwagner.net',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
